version: '3.8'

services:
  db:
    image: postgres:16.1-alpine3.19
    hostname: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
